spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aulas-api
    username: postgres
    password: postgres      
  cache:
    cache-names: person
    guava:
      spec: maximumSize=10,expireAfterAccess=60s