spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: false
  cache:
    cache-names: person
    guava:
      spec: maximumSize=10,expireAfterAccess=60s